# yaml-language-server: $schema=https://json.schemastore.org/github-actions.json
name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t trungnd3/react-tests -f Dockerfile.dev .
      - run: docker run -e CI=true trungnd3/react-tests npm run test

      - name: Generate deployment package
      - run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: React-app
          environment_name: React-app-env
          existing_bucket_name: elasticbeanstalk-us-east-1-391898470917
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
